export const menuOptionsButton = document.getElementById("menu-options-button") as HTMLElement;
export const headMenuContainer = document.getElementById("head-menu-container") as HTMLElement;
export const rightMenuButton = document.getElementById("right-menu-button") as HTMLElement;
export const headMenuItemsContainer = document.getElementById("head-menu-items-container") as HTMLElement;
export const headMenuLineContainer = document.getElementById("head-menu-line-container") as HTMLElement;
export const closeHeadMenuItem = document.getElementById("close-head-menu-item") as HTMLElement;
export const headerPhoto = document.querySelector(".parallax-photo-container .photo") as HTMLElement;
export const parallaxHeader = document.querySelector(".parallax-photo-container .header") as HTMLElement;
export const parallaxParagraph = document.querySelector(".parallax-photo-container .paragraph") as HTMLElement;
